"""initial tables

Revision ID: 0001
Revises: 
Create Date: 2026-07-19 00:40:59.281874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('openalex_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('remaining_reported', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openalex_usage_usage_date'), 'openalex_usage', ['usage_date'], unique=True)
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_key', sa.String(length=300), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('journal', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=300), nullable=True),
    sa.Column('authors_json', sa.JSON(), nullable=False),
    sa.Column('institutions_json', sa.JSON(), nullable=False),
    sa.Column('countries_json', sa.JSON(), nullable=False),
    sa.Column('citations', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('korea_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_index(op.f('ix_papers_paper_key'), 'papers', ['paper_key'], unique=True)
    op.create_index(op.f('ix_papers_year'), 'papers', ['year'], unique=False)
    op.create_table('subfields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('query_kci', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id', 'name', name='uq_subfield_name')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subfield_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_md', sa.Text(), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=True),
    sa.Column('searched_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_count', sa.Integer(), nullable=False),
    sa.Column('sampled', sa.Boolean(), nullable=False),
    sa.Column('batch_job_id', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subfield_id'], ['subfields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subfield_id', 'year', name='uq_analysis_year')
    )
    op.create_table('paper_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_key', sa.String(length=300), nullable=False),
    sa.Column('subfield_id', sa.Integer(), nullable=False),
    sa.Column('tech_summary', sa.Text(), nullable=False),
    sa.Column('achievement_type', sa.String(length=50), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('model_ver', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['subfield_id'], ['subfields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_key', 'subfield_id', 'model_ver', name='uq_extraction')
    )
    op.create_index(op.f('ix_paper_extractions_paper_key'), 'paper_extractions', ['paper_key'], unique=False)
    op.create_table('analysis_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'paper_id', name='uq_analysis_paper')
    )
    op.create_index(op.f('ix_analysis_papers_analysis_id'), 'analysis_papers', ['analysis_id'], unique=False)
    # ### end Alembic commands ###

    fields = sa.table(
        "fields",
        sa.column("name", sa.String),
        sa.column("slug", sa.String),
        sa.column("order_no", sa.Integer),
    )
    op.bulk_insert(fields, [
        {"name": "반도체·디스플레이", "slug": "semiconductor", "order_no": 1},
        {"name": "이차전지", "slug": "battery", "order_no": 2},
        {"name": "첨단 모빌리티", "slug": "mobility", "order_no": 3},
        {"name": "차세대 원자력", "slug": "nuclear", "order_no": 4},
        {"name": "첨단 바이오", "slug": "bio", "order_no": 5},
        {"name": "우주항공·해양", "slug": "space-ocean", "order_no": 6},
        {"name": "수소", "slug": "hydrogen", "order_no": 7},
        {"name": "사이버보안", "slug": "cybersecurity", "order_no": 8},
        {"name": "인공지능", "slug": "ai", "order_no": 9},
        {"name": "차세대 통신", "slug": "communication", "order_no": 10},
        {"name": "첨단로봇·제조", "slug": "robotics", "order_no": 11},
        {"name": "양자", "slug": "quantum", "order_no": 12},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_papers_analysis_id'), table_name='analysis_papers')
    op.drop_table('analysis_papers')
    op.drop_index(op.f('ix_paper_extractions_paper_key'), table_name='paper_extractions')
    op.drop_table('paper_extractions')
    op.drop_table('analyses')
    op.drop_table('subfields')
    op.drop_index(op.f('ix_papers_year'), table_name='papers')
    op.drop_index(op.f('ix_papers_paper_key'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_openalex_usage_usage_date'), table_name='openalex_usage')
    op.drop_table('openalex_usage')
    op.drop_table('fields')
    # ### end Alembic commands ###
